#Minecraft server properties
#Wed Aug 19 22:11:52 EDT 2026
accepts-transfers=false
allow-end=true
allow-flight=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=normal
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=4
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla,artifacts,artifactscrafting,balm,bunnyboots,collective,comforts,explorerscompass,explorify,fabric-convention-tags-v2,geophilic,hardcorerevival,mr_lukis_grandcapitals,naturescompass,too_expensive_removed,villagerinabucket,waystones
level-name=world
level-seed=8003843
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=59bsyx1GXJrWTEMKYurk5Nu3eydcC9dpDcCReSUr
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=6
max-tick-time=60000
max-world-size=3000
motd=Froggo SMP Season 5
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=your_rcon_password
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=12
white-list=true
